version: 1.0.{build}
image: Visual Studio 2015
configuration: Debug
platform: x64
install:
- ps: >-
$vsixPath = "$($env:USERPROFILE)\BoostUnitTestAdapter.vsix"
(New-Object Net.WebClient).DownloadFile('https://visualstudiogallery.msdn.microsoft.com/5f4ae1bd-b769-410e-8238-fb30beda987f/file/105652/27/BoostUnitTestAdapter.vsix', $vsixPath)
cmd  /c "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe" /q /a $vsixPath
echo $?
echo "INSTALL SCRIPT FINISH"
cd C:\projects\boostunittest2
cache: C:\projects\boostunittest2\packages

before_build:
- cmd: >-
nuget restore
choco install codecov
build:
project: C:\projects\boostunittest2\BoostUnitTest2.sln
verbosity: minimal
after_build:
- cmd:
test_script:
- ps: "$testconsole = \"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\\"\n\n$VisualCoverage = \"C:\\projects\\boostunittest2\\dep\\VisualCoverage\\\"\n\n$unittestspath = $env:USERPROFILE\n\ncd $testconsole\n\n.\\vstest.console.exe /UseVsixExtensions:true /Platform:x64 /Enablecodecoverage /InIsolation \"C:\\projects\\boostunittest2\\x64\\Debug\\BoostUnitTest2.exe\"\n\n$testReport = get-childitem 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\TestResults\\*\\*.coverage'\n\necho $testReport.name\n\ncd .\\TestResults\n\n$dir = dir .\\ | ?{$_.PSISContainer} \nforeach ($d in $dir){\n$directoryInfo = Get-ChildItem $d| Measure-Object\nif ($directoryInfo.count -eq 0){\nRemove-Item -Recurse -Force $d\n}\n}\n\n$testFolder = dir -Directory\n\ncd $VisualCoverage \n\n.\\VisualCoverage.exe -i $testReport --clover ConvertedReport.xml\n\ncat \".\\ConvertedReport.xml\"\n\ncodecov -f .\\ConvertedReport.xml"
