version: 1.0.{build}
image: Visual Studio 2015
configuration: Debug
platform: x64
install:

- ps: >-
    $vsixPath = "$($env:USERPROFILE)\BoostUnitTestAdapter.vsix"
    (New-Object Net.WebClient).DownloadFile('https://visualstudiogallery.msdn.microsoft.com/5f4ae1bd-b769-410e-8238-fb30beda987f/file/105652/27/BoostUnitTestAdapter.vsix', $vsixPath)
    cmd  /c "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe" /q /a $vsixPath
    echo $?
    echo "INSTALL SCRIPT FINISH"

cache: C:\projects\boostunittest2\packages
before_build:
- cmd: >-
    nuget restore
    choco install codecov

build:
  project: C:\projects\boostunittest2\BoostUnitTest2.sln
  verbosity: minimal
test_script:
- ps: >-
$testconsole = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\"
$VisualCoverage = "C:\projects\boostunittest2\dep\VisualCoverage\"
$unittestspath = $env:USERPROFILE

cd $testconsole

.\vstest.console.exe /UseVsixExtensions:true /Platform:x64 /Enablecodecoverage /InIsolation "C:\projects\boostunittest2\x64\Debug\BoostUnitTest2.exe"

$testReport = get-childitem 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\TestResults\*\*.coverage'

echo $testReport.name

cd .\TestResults

$dir = dir .\ | ?{$_.PSISContainer}
foreach ($d in $dir){
$directoryInfo = Get-ChildItem $d| Measure-Object
if ($directoryInfo.count -eq 0){
Remove-Item -Recurse -Force $d
}
}

$testFolder = dir -Directory

cd $VisualCoverage

.\VisualCoverage.exe -i $testReport --clover ConvertedReport.xml

codecov -f .\ConvertedReport.xml
